### ISSUE TITLE
Guzzle deprecated message

### ISSUE THREAD

**Issue by f3l1x** [contributte/comgate#12]
https://travis-ci.org/github/contributte/comgate/jobs/735687987

![image](https://user-images.githubusercontent.com/538058/96570667-eafbdb00-12ca-11eb-99eb-bf53006fb4d6.png)

**Comment by f3l1x** [comment]
@cendak Could you please take a look?

**Comment by trejjam** [comment]
Should be solved by #13

**Comment by radimvaculik** [comment]
@f3l1x Please, close this issue. Solved.
