### ISSUE TITLE
Price parameter should be float or may not be multiplied by 100

### ISSUE THREAD

**Issue by jelen07** [contributte/comgate#2]
### Problem
I want to buy a product which cost 1024,50 CZK.

### Solution
1. The first parameter **$price** in `Payment::of()` should be a float, but there is a threat, that the price will be to more decimal places (>2).
1. Do not convert the price in this method - leave the responsibility to the implementer.

Check this out - https://github.com/contributte/comgate/blob/master/src/Entity/Payment.php#L69

@f3l1x Shlould I send PR? Which option?

---

More things to do...
### Payment validation
Payment should be at least in total [10 CZK](https://www.comgate.cz/cz/protokol-api). Shold it throw an exception?

**Comment by jelen07** [comment]
# Gateway URL
@f3l1x Could it be in a constant?
https://github.com/contributte/comgate/blob/master/src/DI/ComgateExtension24.php#L19
https://github.com/contributte/comgate/blob/master/src/DI/ComgateExtension.php#L24

I'm using a client (without Nette DI) and would like to use the URL from this extension.

**Comment by f3l1x** [comment]
Hi @jelen07. Thanks for your points. Could you please prepare a PR with minimal price validation and acepting 1024,50 (float) but internally handle it as 102450 (int)?

**Comment by jelen07** [comment]
Yup, np.
Ad accepting floats) So when the price has more than 2 decimal places, the exception will be thrown, ok?

**Comment by f3l1x** [comment]
Yes, throw exception.

**Comment by hrach** [comment]
Never ever accept a float. There should be just an interface (another method?) accepting money with cents. E.g. Payment::ofMilis()

**Comment by f3l1x** [comment]
You're right @hrach, thanks.

**Comment by jelen07** [comment]
I was thinking about adding the method `Payment::ofMinor()` but there would be more disadvantages than profits. You should add some money library (e.g. brick/money)... now it is independent and passes on responsibility to the implementator.

**Comment by f3l1x** [comment]
Hi @jelen07, could you please add brick/money lib?

**Comment by trejjam** [comment]
Hi, I hit the same issue. I prepare the PR.

**Comment by jelen07** [comment]
@trejjam Thx. I'll get to the Comgate first in November.

**Comment by f3l1x** [comment]
Resolved via #11.
