### ISSUE TITLE
Add support for recurring payments

### ISSUE THREAD

**Issue by vaclavgreif** [contributte/comgate#23]
To support recurring payments I created a subclass of Payment, and added `recurring` method to the Payment service. Would it be possible to add support for the recurring payments to the main SDK?

```php
<?php

namespace WpifyWooComgate\Modules\Comgate;

class Payment extends \WpifyWooComgateDeps\Contributte\Comgate\Entity\Payment {
	private $initRecurring = false;
	/** @var string */
	private $initRecurringId = '';

	/**
	 * @return mixed[]
	 */
	public function toArray(): array {
		$data = [
			'price'       => $this->getPrice(),
			'curr'        => $this->getCurr(),
			'label'       => $this->getLabel(),
			'refId'       => $this->getRefId(),
			'method'      => $this->getMethod(),
			'email'       => $this->getEmail(),
			'prepareOnly' => $this->isPrepareOnly() ? 'true' : 'false',
			'country'     => $this->getCountry(),
			'lang'        => $this->getLang(),
		];

		if ( $this->isInitRecurring() ) {
			$data['initRecurring'] = $this->isInitRecurring();
		}
		if ( $this->initRecurringId ) {
			$data['initRecurringId'] = $this->initRecurringId;
		}

		return $data;
	}

	public function isInitRecurring(): bool {
		return $this->initRecurring;
	}

	/**
	 * @param bool $initRecurring
	 */
	public function setInitRecurring( bool $initRecurring ): void {
		$this->initRecurring = $initRecurring;
	}

	/**
	 * @return string
	 */
	public function getInitRecurringId(): string {
		return $this->initRecurringId;
	}

	/**
	 * @param string $initRecurringId
	 */
	public function setInitRecurringId( string $initRecurringId ): void {
		$this->initRecurringId = $initRecurringId;
	}
}

```

```php
public function recurring( \WpifyWooComgateDeps\Contributte\Comgate\Entity\Payment $payment ): \WpifyWooComgateDeps\Contributte\Comgate\Http\Response {
		$data = $payment->toArray();

		return $this->client->post( 'recurring', $data );
	}

```

**Comment by MartinMystikJonas** [comment]
@f3l1x I will need this recurring payments function too. I can prepare PR based on code provided by @vaclavgreif. But I think recurring payments should be seaprate entity because it has similar but not same set of parameters and normal payment. What do you think?

**Comment by f3l1x** [comment]
Yep, please separate entity and prepare PR. Thank you.

**Comment by MartinMystikJonas** [comment]
I found something weird in current Payment implementation. It contains fields like `payerId` and `phone` that are not used for payment data and are not even supported for payment data. According to Comgate docs these fields are present only in payment notification hook.

Is there any reason why these params are there? Or is it just mistake and I should remove them?

ALso there are fields like `verification` and `embeded` that could be set but are ignored in payment data. But it should se supported. Should I fix that too?

**Comment by f3l1x** [comment]
Yes please, fix it. Comgate docs are evolving and some fields might be wrong. :-)

**Comment by MartinMystikJonas** [comment]
PR #33

**Comment by MartinMystikJonas** [comment]
This could be closed
