### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by MartinMystikJonas** [contributte/comgate#37]
Is here reason why new version requires brick/money ^0.9? There is problem that brick/money 0.9 requires brick/math ^0.12 but ramsey/uuid we use too in our app is not yet compatible with brick/math 0.12. So we have conflict of required versions of brick/math when we want o upgrade.

**Comment by f3l1x** [comment]
Just standard dependency upgrade path. If you prepare PR, we can support lower version also.

**Comment by MartinMystikJonas** [comment]
PR #38
